export default {
  SET_CHANNELS: 'SET_CHANNELS',
  SET_MESSAGES: 'SET_MESSAGES',
  ADD_MESSAGE: 'ADD_MESSAGE',
  SET_PREVIEW_MESSAGES: 'SET_PREVIEW_MESSAGES',
  UPDATE_PREVIEW_MESSAGES: 'UPDATE_PREVIEW_MESSAGES',
  SET_CHAT_INITIALIZED: 'SET_CHAT_INITIALIZED',
  ADD_CHANNEL: 'ADD_CHANNEL',
  SET_SELECTED_CHANNEL: 'SET_SELECTED_CHANNEL',
}
